services:
  mongodb:
    image: mongo:7.0
    container_name: urlshortener-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  urlshortener:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/urlshortener

volumes:
  mongo-data:
