urlshortener:
  domain: http://localhost:8080

spring:
  data:
    mongodb:
      database: ${MONGO_DB:urlshortener}
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      auto-index-creation: true

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    path: /error